name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ls -A
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls -A
      - run: echo done
